# Generated by Django 3.2.5 on 2021-08-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210715_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_code', models.CharField(max_length=255)),
                ('city_desc', models.CharField(max_length=255)),
                ('taluka_code', models.CharField(max_length=255)),
                ('taluka_desc', models.CharField(max_length=255)),
                ('district_code', models.CharField(max_length=255)),
                ('district_desc', models.CharField(max_length=255)),
                ('region_code', models.CharField(max_length=255)),
                ('region_desc', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=255)),
                ('state_desc', models.CharField(max_length=255)),
                ('zone_code', models.CharField(max_length=255)),
                ('zone_desc', models.CharField(max_length=255)),
                ('zone_geo_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
                ('lng', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'node_address',
            },
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_class_details', models.CharField(max_length=255)),
                ('customer_class_desc', models.CharField(max_length=255)),
                ('customer_classification', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'node_customer_master',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depot_code', models.CharField(max_length=255)),
                ('depot_desc', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'node_depot',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=255)),
                ('facility_code', models.CharField(max_length=255)),
                ('facility_desc', models.CharField(max_length=255)),
                ('facility_processing', models.CharField(max_length=255)),
                ('facility_sub_type', models.CharField(max_length=255)),
                ('fixed_cost', models.CharField(max_length=255)),
                ('handling_charge_hook', models.CharField(max_length=255)),
                ('handling_charge_non_hook', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.CharField(max_length=255)),
                ('scenario', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('exception_flag', models.CharField(max_length=255)),
                ('exception_msg', models.CharField(max_length=255)),
                ('validated_by', models.CharField(max_length=255)),
                ('mfg_code', models.CharField(max_length=255)),
                ('plant_category', models.CharField(max_length=255)),
                ('godown_location', models.CharField(max_length=255)),
                ('i2_code', models.CharField(max_length=255)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.address')),
                ('depot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.depot')),
            ],
            options={
                'db_table': 'node_facility',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.CharField(max_length=255)),
                ('scenario', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('exception_flag', models.CharField(max_length=255)),
                ('exception_msg', models.CharField(max_length=255)),
                ('validated_by', models.CharField(max_length=255)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.address')),
                ('cust_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.customermaster')),
                ('depot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.depot')),
            ],
            options={
                'db_table': 'node_customer',
            },
        ),
    ]
